server:
  port: 8000
spring:
  application:
    name: gateway-service
  zipkin:
    enabled: true
    locator:
      discovery:
        enabled: true
    sender:
      type: web
    base-url: http://192.168.2.40:9411
    service:
      name: gateway-service
  sleuth:
    sampler:
      probability: 1
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.40:8848
    sentinel:
      transport:
        port: 18750
        dashboard: 192.168.2.40:8748
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}
        - id: lesson
          uri: lb://lesson-service
          predicates:
            - Path=/lesson/**
          filters:
            - RewritePath=/lesson/(?<path>.*), /$\{path}
logging:
  level:
    com:
      alibaba:
        nacos: warn