server:
  port: 8000
spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  zipkin:
    enabled: true
    locator:
      discovery:
        enabled: true
    sender:
      type: web
    base-url: http://192.168.2.40:9411
    service:
      name: gateway-service
  sleuth:
    sampler:
      probability: 1
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}
        - id: lesson
          uri: lb://lesson-service
          predicates:
            - Path=/lesson/**
          filters:
            - RewritePath=/lesson/(?<path>.*), /$\{path}
        - id: oauth
          uri: lb://oauth-service
          predicates:
            - Path=/oauth/**
          filters:
            - RewritePath=/oauth/(?<path>.*), /$\{path}
logging:
  level:
    com:
      alibaba:
        nacos: warn
swagger:
  title: bellatrix
  description: "bellatrix"
  version: 1.0
  license: ""
  licenseUrl: http://baidu.com
  terms-of-service-url: http://baidu.com
  contact:
    name: zhangjun
    email: zhangjun@123.com
    url: http://baidu.com
  authorization:
    name: pig4cloud OAuth
    auth-regex: ^.*$