server:
  port: 9002
spring:
  application:
    name: lesson-service
  profiles:
    active: dev
  zipkin:
    enabled: true
    locator:
      discovery:
        enabled: true
    sender:
      type: web
    base-url: http://192.168.2.40:9411
    service:
      name: lesson-service
  sleuth:
    sampler:
      probability: 1